[package]
name = "git-reminder-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
ureq = { version = "2.6.2" }
chrono = { version = "0.4.23", features = ["serde"] }
cron = { version = "0.12.0" }

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
